/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package th.co.entronica.apollo.testametorprovider.view.content;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import th.co.entronica.apollo.testametorprovider.controller.MainController;
import th.co.entronica.apollo.testametorprovider.controller.ManageScriptController;
import th.co.entronica.apollo.testametorprovider.controller.MasterController;

/**
 *
 * @author Pop
 */
public class ManageScriptPanel extends javax.swing.JPanel {

   /**
    * Creates new form ManageScriptPanel
    */
   private DefaultListModel model;
   private String textArea;
   private String pathProject;
   private File fileEdit;
   private String backUpContent = "";
   private String line = "";
   private ManageScriptController msc;

   public ManageScriptPanel(String pathPro) {
   }

   public ManageScriptPanel(ManageScriptController manageScrtipController) {
      msc = manageScrtipController;
      initComponents();

   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      dialogNewScript = new javax.swing.JDialog();
      lblScriptName = new javax.swing.JLabel();
      txtFScriptName = new javax.swing.JTextField();
      btnOkScript = new javax.swing.JButton();
      btnCancelScript = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      manageList = new javax.swing.JList();
      jScrollPane2 = new javax.swing.JScrollPane();
      editFileText = new javax.swing.JTextArea();
      btnCancelEditScript = new javax.swing.JButton();
      btnSaveEditScript = new javax.swing.JButton();
      btnNewScript = new javax.swing.JButton();

      dialogNewScript.setTitle("New Project");

      lblScriptName.setText("Script Name");

      btnOkScript.setText("Ok");
      btnOkScript.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOkScriptActionPerformed(evt);
         }
      });

      btnCancelScript.setText("Cancel");
      btnCancelScript.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelScriptActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout dialogNewScriptLayout = new javax.swing.GroupLayout(dialogNewScript.getContentPane());
      dialogNewScript.getContentPane().setLayout(dialogNewScriptLayout);
      dialogNewScriptLayout.setHorizontalGroup(
         dialogNewScriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dialogNewScriptLayout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(dialogNewScriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(dialogNewScriptLayout.createSequentialGroup()
                  .addComponent(lblScriptName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(txtFScriptName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(dialogNewScriptLayout.createSequentialGroup()
                  .addGap(95, 95, 95)
                  .addComponent(btnOkScript)
                  .addGap(18, 18, 18)
                  .addComponent(btnCancelScript)))
            .addContainerGap(30, Short.MAX_VALUE))
      );
      dialogNewScriptLayout.setVerticalGroup(
         dialogNewScriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dialogNewScriptLayout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(dialogNewScriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblScriptName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtFScriptName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(dialogNewScriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnCancelScript)
               .addComponent(btnOkScript))
            .addContainerGap(26, Short.MAX_VALUE))
      );

      setPreferredSize(new java.awt.Dimension(500, 450));

      manageList.setModel(new javax.swing.AbstractListModel() {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      manageList.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            manageListMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(manageList);

      editFileText.setColumns(20);
      editFileText.setRows(5);
      editFileText.setEnabled(false);
      jScrollPane2.setViewportView(editFileText);

      btnCancelEditScript.setText("cancel");
      btnCancelEditScript.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelEditScriptActionPerformed(evt);
         }
      });

      btnSaveEditScript.setText("save");
      btnSaveEditScript.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveEditScriptActionPerformed(evt);
         }
      });

      btnNewScript.setText("New Script");
      btnNewScript.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnNewScriptActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(btnNewScript)
                  .addGap(9, 9, 9)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(9, 274, Short.MAX_VALUE)
                  .addComponent(btnSaveEditScript)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnCancelEditScript)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnCancelEditScript)
               .addComponent(btnSaveEditScript)
               .addComponent(btnNewScript))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents

    private void btnCancelEditScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditScriptActionPerformed
      int returnYesNoOptionpane = matchTextField();
      if (returnYesNoOptionpane == 1 || returnYesNoOptionpane == -1) {
         editFileText.setText(editFileText.getText());

         editFileText.setEnabled(true);
         manageList.setEnabled(false);
      } else {
         editFileText.setText(backUpContent);

         editFileText.setEnabled(false);
         manageList.setEnabled(true);
         btnNewScript.setEnabled(true);
      }
    }//GEN-LAST:event_btnCancelEditScriptActionPerformed

    private void manageListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageListMouseClicked

       if (evt.getClickCount() == 2) {
          editFileText.setVisible(true);
          editFileText.setEnabled(true);
          manageList.setEnabled(false);
          btnNewScript.setEnabled(false);
          appendTextField();

       } else if (evt.getClickCount() == 1) {
          manageList.setVisible(true);
          appendTextField();
       }
    }//GEN-LAST:event_manageListMouseClicked

    private void btnSaveEditScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditScriptActionPerformed
       try {
          String content = editFileText.getText();
          FileWriter fw = new FileWriter(fileEdit.getAbsoluteFile());
          BufferedWriter bw = new BufferedWriter(fw);
          bw.write(content);
          bw.close();
          backUpContent = editFileText.getText();
          editFileText.setEnabled(false);

       } catch (IOException e) {
          e.printStackTrace();
       }
       manageList.setEnabled(true);
       btnNewScript.setEnabled(true);
    }//GEN-LAST:event_btnSaveEditScriptActionPerformed

    private void btnNewScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewScriptActionPerformed
       dialogNewScript.show();
       dialogNewScript.setSize(380, 160);
       manageList.setEnabled(true);
    }//GEN-LAST:event_btnNewScriptActionPerformed

   private void btnCancelScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelScriptActionPerformed
      dialogNewScript.dispose();
      txtFScriptName.setText("");
   }//GEN-LAST:event_btnCancelScriptActionPerformed

   private void btnOkScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkScriptActionPerformed

      String path = pathProject + "/TestScript/" + txtFScriptName.getText() + ".txt";
      fileEdit = new File(path);

      FileWriter writer;
      try {
         if (fileEdit.exists()) {

            JOptionPane.showMessageDialog(this,
                    "This file already exists.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
         } else {

            writer = new FileWriter(fileEdit, true);
            writer.write("");
            writer.close();

            System.out.println("Write success!");
            dialogNewScript.dispose();
         }
         initValue();

      } catch (IOException e) {
         e.printStackTrace();
      }
   }//GEN-LAST:event_btnOkScriptActionPerformed
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancelEditScript;
   private javax.swing.JButton btnCancelScript;
   private javax.swing.JButton btnNewScript;
   private javax.swing.JButton btnOkScript;
   private javax.swing.JButton btnSaveEditScript;
   private javax.swing.JDialog dialogNewScript;
   private javax.swing.JTextArea editFileText;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JLabel lblScriptName;
   private javax.swing.JList manageList;
   private javax.swing.JTextField txtFScriptName;
   // End of variables declaration//GEN-END:variables

   private void addListManage(String pathPro) {
      pathProject = pathPro;
      try {
         model = new DefaultListModel();
         File filePath = new File(pathPro + "/TestScript/");
         File[] fileList = filePath.listFiles();
         model.removeAllElements();
         manageList.setModel(model);
         for (File file : fileList) {
            if (file.isFile()) {
               String fileName = file.getName();
               model.addElement(fileName);
               manageList.setModel(model);
            }
         }
      } catch (Exception e) {
         e.printStackTrace();
      }


   }

   public int matchTextField() {
      int n = 0;
      if (!(backUpContent.equals(editFileText.getText()))) {
         n = JOptionPane.showConfirmDialog(
                 this,
                 "This file has modified content" + "\n" + "Do you want to exit ?",
                 "An Inane Question",
                 JOptionPane.YES_NO_OPTION);
      }
      return n;
   }

   public void appendTextField() {
      if (manageList.getModel().getSize() != 0) {
         editFileText.setText("");
         textArea = (String) manageList.getSelectedValue();
         String path = pathProject + "/TestScript/" + textArea;
         fileEdit = new File(path);

         try {
            BufferedReader br = new BufferedReader(new FileReader(fileEdit));

            while ((line = br.readLine()) != null) {
               editFileText.append(line + "\n");

            }
            backUpContent = editFileText.getText();
            br.close();
         } catch (IOException e) {
            e.printStackTrace();
         }
      }
   }

   public void initValue() {
      MainController mainController = MasterController.getInstance().getMainController();
      addListManage(mainController.getProjectPath() + "/" + mainController.getProjectName());
   }
}